FROM python:3.8

# bash를 사용하기 위해 설치
#RUN apk update && \
#    apk add --no-cache \
#    bash

# python 기본 패키지
#RUN apk add --update build-base python3-dev py-pip

#ENV LIBRARY_PATH=/lib:/usr/lib

RUN pip install --upgrade pip

WORKDIR /www/app
COPY . ./

RUN pip install mysqlclient
RUN pip install -r requirements.txt
# RUN python ./src/manage.py db:migration
CMD python ./src/manage.py run:prod