POST http://127.0.0.1:5000/api/users HTTP/1.1
content-type: application/json

{
    "id": "test3@email.com",
    "name": "test3",
    "password": "password"
}

###

GET http://127.0.0.1:5000/api/users HTTP/1.1
content-type: application/json

